name: Sync `autoupdate-ca-test` Branch

on:
  push:
    branches:
      - master
      - ca-test

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Create
        run: |
          git checkout $(git rev-parse master)
          git cherry-pick origin/ca-test
          HEAD=$(git rev-parse HEAD)
          git checkout -B autoupdate-ca-test
          git reset --hard ${HEAD}
      - name: Push
        run: |
          git push origin autoupdate-ca-test -f