# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_lostattractor 57EDCBEDDE7ABA6B44377FF2B96725F36430B3D1
  - &device_calaptopg14 age197ftfqlm75q9vlcc5mu6j5a90fh8lfw0cecxvw968xmrkgwjg59qledtwm
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - pgp:
      - *admin_lostattractor
      age:
      - *device_calaptopg14